---
- name: Check if firewalld service exists
  stat: path=/usr/lib/systemd/system/firewalld.service
  register: firewalld_service

- name: Ensure that firewalld is completely disabled
  service:
    name: firewalld
    state: stopped
    enabled: false
    masked: true
  become: true
  when: firewalld_service.stat.exists

- name: Run RHEL version specific tasks
  include_tasks: "{{ ansible_os_family }}-{{ ansible_distribution_major_version}}.yml"
...
