---
- name: Restart CSF
  service:
    name: csf
    state: restarted
    enabled: true
  become: true
  async: 15
  poll: 5
  when: csfstarted is not changed

- name: Restart LFD
  service:
    name: lfd
    state: restarted
    enabled: true
  become: true
  async: 15
  poll: 5
  when: lfdstarted is not changed
