# yamllint disable-file
---
name: Yamllint

on: [push, pull_request]

jobs:
  yamllint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint .yml files
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
